# .streamlit/config.toml
[server]
headless = true
enableCORS = true
enableXsrfProtection = true
sslCertFile = "certificate/server.crt"
sslKeyFile = "certificate/server.key"

[theme]
primaryColor="#FFFFF"
backgroundColor="#0f0f0f"
secondaryBackgroundColor="#FFFFF"
textColor="#FFFFF"
font="sans serif"